// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7JbtveEsYpKOXyOteSYx1P-vpKbH9Csk',
    appId: '1:292894067063:web:2b7e0b6e8056e047313972',
    messagingSenderId: '292894067063',
    projectId: 'store-e1838',
    authDomain: 'store-e1838.firebaseapp.com',
    storageBucket: 'store-e1838.appspot.com',
    measurementId: 'G-4VGLCPSX6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxxVFwUv1bEEglfRTHTrhQtVn2ZfFvVlE',
    appId: '1:292894067063:android:1a16c9dc8fe33d7d313972',
    messagingSenderId: '292894067063',
    projectId: 'store-e1838',
    storageBucket: 'store-e1838.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASX9VwFkEdTEQtiKvF9nfglKWvNNVlLUE',
    appId: '1:292894067063:ios:22370ae1daf8efe3313972',
    messagingSenderId: '292894067063',
    projectId: 'store-e1838',
    storageBucket: 'store-e1838.appspot.com',
    iosBundleId: 'com.example.smartstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASX9VwFkEdTEQtiKvF9nfglKWvNNVlLUE',
    appId: '1:292894067063:ios:22370ae1daf8efe3313972',
    messagingSenderId: '292894067063',
    projectId: 'store-e1838',
    storageBucket: 'store-e1838.appspot.com',
    iosBundleId: 'com.example.smartstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7JbtveEsYpKOXyOteSYx1P-vpKbH9Csk',
    appId: '1:292894067063:web:3d3d60f7d1dfbfc6313972',
    messagingSenderId: '292894067063',
    projectId: 'store-e1838',
    authDomain: 'store-e1838.firebaseapp.com',
    storageBucket: 'store-e1838.appspot.com',
    measurementId: 'G-0CRRFBY40N',
  );
}
